import ArrowIcon from '../ui/ArrowIcon'
import GitHubIcon from '../ui/GitHubIcon'
import TagList from '../ui/TagList'

function ProjectCard({ project }) {
  return <article className="group reveal border border-[var(--line)] bg-[rgba(13,17,29,.5)] transition-all duration-300 hover:-translate-y-[6px] hover:border-indigo-400/40"><a className={`project-overlay relative isolate flex h-[230px] justify-between overflow-hidden border-b border-[var(--line)] bg-[#111522] p-[22px] max-[850px]:h-[190px] ${project.accent}`} href={project.live} target="_blank" rel="noreferrer" aria-label={`View ${project.title}`}><img className="absolute -z-2 inset-0 size-full object-cover object-top transition-all duration-450 group-hover:scale-[1.035] group-hover:saturate-110" src={project.image} alt={`Preview of ${project.title}`} loading="lazy" /><span className="self-start rounded-[2px] border border-white/10 bg-[rgba(7,9,18,.72)] px-2 py-[5px] font-['DM_Mono'] text-[.67rem] text-[#e7e9f5]">ML / {project.number}</span><strong className="self-end font-['DM_Mono'] text-[4.5rem] text-white/22">{project.number}</strong></a><div className="p-[26px]"><div><p className="m-0 font-['DM_Mono'] text-[.67rem] uppercase text-[var(--accent-bright)]">Project {project.number}</p><h3 className="mt-2 mb-5 text-xl font-medium">{project.title}</h3></div><p className="min-h-[66px] text-[.79rem] leading-[1.65] text-[var(--muted)]">{project.description}</p><TagList items={project.tags} /><div className="mt-[27px] flex items-center gap-[22px] border-t border-[var(--line)] pt-[18px]"><a className="project-link relative inline-flex items-center gap-[7px] pb-[5px] font-['DM_Mono'] text-[.72rem] tracking-[.03em] text-[var(--green)] transition-colors hover:text-white [&_svg]:size-[15px] [&_svg]:transition-transform hover:[&_svg]:translate-x-0.5" href={project.live} target="_blank" rel="noreferrer">Demo <ArrowIcon /></a><a className="project-link relative inline-flex items-center gap-[7px] pb-[5px] font-['DM_Mono'] text-[.72rem] tracking-[.03em] text-[#d7dae6] transition-colors hover:text-white [&_svg]:size-[15px] [&_svg]:transition-transform hover:[&_svg]:translate-x-0.5" href={project.repo} target="_blank" rel="noreferrer"><GitHubIcon /> Code</a></div></div></article>
}

export default ProjectCard
