import SectionHeading from '../components/ui/SectionHeading'

const profileImage = `${import.meta.env.BASE_URL}profile.png`

function AboutSection() {
  return <section id="sobre-mi" className="mx-auto w-[min(1180px,calc(100%_-_48px))] border-t border-[var(--line)] py-32 max-[850px]:py-[90px] max-[520px]:w-[min(1180px,calc(100%_-_30px))]"><SectionHeading eyebrow="01 / About" title="Curious mind. Practical approach." /><div className="grid grid-cols-[1.25fr_.75fr] items-center gap-[12vw] max-[850px]:grid-cols-1 max-[850px]:gap-[70px]"><div className="reveal text-[.95rem] leading-[1.8] text-[var(--muted)]"><p className="text-[1.3rem] leading-[1.55] text-[#e1e4ee]">I turn ideas into simple, useful web experiences.</p><p>I study IT Engineering at UNAN–León and build frontend projects with a focus on usability and mobile-friendly layouts.</p><p>As a <strong className="text-[#d8dbeb]">Web Developer</strong>, I want to build and maintain website features, improve performance and collaborate with designers and marketers.</p><div className="mt-8 flex flex-wrap gap-[10px]"><span className="rounded-[2px] border border-[var(--line)] px-[10px] py-[7px] font-['DM_Mono'] text-[.69rem] text-[#aeb3c7]">Dependable</span><span className="rounded-[2px] border border-[var(--line)] px-[10px] py-[7px] font-['DM_Mono'] text-[.69rem] text-[#aeb3c7]">Self-directed</span><span className="rounded-[2px] border border-[var(--line)] px-[10px] py-[7px] font-['DM_Mono'] text-[.69rem] text-[#aeb3c7]">Detail-oriented</span></div></div><div className="reveal relative max-w-[380px] justify-self-end max-[850px]:justify-self-center"><div className="portrait-gradient overflow-hidden border border-[var(--line)]"><img className="block w-full saturate-80" src={profileImage} alt="Professional portrait of Maynor López" /></div><div className="absolute -bottom-7 -left-7 flex min-w-[170px] flex-col border border-[var(--line)] bg-[#0c101b] px-[18px] py-[14px]"><span className="font-['DM_Mono'] text-[.68rem] uppercase text-[#70768b]">Based in</span><strong className="mt-[5px] text-[.8rem]">León, Nicaragua</strong></div></div></div></section>
}

export default AboutSection
