import { useEffect, useState } from 'react'
import './App.css'
import profileImage from '../public/profile.png'
import Header from './components/Header'

const baseUrl = import.meta.env.BASE_URL

const skills = [
  { number: '01', title: 'Frontend', description: 'Clear, user-friendly layouts for desktop and mobile.', items: ['HTML5', 'CSS3', 'JavaScript', 'React', 'Tailwind CSS'] },
  { number: '02', title: 'Tools', description: 'Version control, UI design and a maintainable workflow.', items: ['Git', 'GitHub', 'Vite', 'Figma', 'VS Code'] },
  { number: '03', title: 'Learning', description: 'Building on basic Node.js knowledge to grow toward full-stack development.', items: ['Node.js (basic)', 'C#', '.NET', 'ASP.NET Core', 'REST APIs'] },
]
const featuredProjects = [
  { number: '01', title: 'Product List with Cart', description: 'Responsive catalog with quantity controls, a shopping cart and order confirmation.', tags: ['JavaScript', 'Responsive', 'UI State'], live: 'https://mlopezl.github.io/product-list-with-card/', repo: 'https://github.com/mlopezl/product-list-with-card', image: `${baseUrl}projects/product-cart.jpg`, accent: 'from-emerald-500/25 to-indigo-500/5' },
  { number: '02', title: 'Browser Extension Manager', description: 'Interactive dashboard with filters, extension controls and theme switching.', tags: ['JavaScript', 'Filters', 'Responsive UI'], live: 'https://mlopezl.github.io/my-version-of-browser-extensions-manager-ui-main-challenge/', repo: 'https://github.com/mlopezl/my-version-of-browser-extensions-manager-ui-main-challenge', image: `${baseUrl}projects/extension-manager.jpg`, accent: 'from-indigo-500/25 to-emerald-500/5' },
  { number: '03', title: 'Contact Form', description: 'Responsive form with input validation and clear error and success feedback.', tags: ['HTML5', 'CSS3', 'Validation'], live: 'https://mlopezl.github.io/contact-info-form-challenge/', repo: 'https://github.com/mlopezl/contact-info-form-challenge', image: `${baseUrl}projects/contact-form.jpg`, accent: 'from-emerald-400/20 to-cyan-500/5' },
]
const otherProjects = [
  { title: 'Social Media Dashboard', category: 'Light and dark themes', live: 'https://mlopezl.github.io/social-media-dashboard-with-theme-switcher/', repo: 'https://github.com/mlopezl/social-media-dashboard-with-theme-switcher' },
  { title: 'Tip Calculator', category: 'Calculations and interaction', live: 'https://mlopezl.github.io/tip-calculator-app-challenge/', repo: 'https://github.com/mlopezl/tip-calculator-app-challenge' },
  { title: 'Conference Ticket Generator', category: 'Form and live preview', live: 'https://mlopezl.github.io/My-version-of-conference-ticket-generator-challenge/', repo: 'https://github.com/mlopezl/My-version-of-conference-ticket-generator-challenge' },
  { title: 'Insure landing page', category: 'Responsive layout', live: 'https://mlopezl.github.io/Insure-Landing-Page/', repo: 'https://github.com/mlopezl/Insure-Landing-Page' },
]
const experience = [
  { period: '2022 — Present', role: 'Customer Service Representative', company: 'D&R', summary: 'Handling inquiries, resolving problems and following up to support a positive customer experience.' },
  { period: '2020 — 2022', role: 'Professional Recruiter', company: 'Accedo Technologies', summary: 'Candidate screening, phone interviews and recruitment coordination.' },
  { period: '2017 — 2022', role: 'Social Responsibility Supervisor', company: 'Ingenio San Antonio', summary: 'Coordinating community programs and working with teams on education, health and infrastructure projects.' },
]
const courses = [
  { title: 'HTML and CSS in Depth', date: 'Feb 2025', certificate: `${baseUrl}certificates/html-css-profundo.pdf` },
  { title: 'JavaScript Fundamentals', date: 'Mar 2025', certificate: `${baseUrl}certificates/fundamentos-javascript.pdf` },
  { title: 'JavaScript: DOM Manipulation', date: 'Mar 2025', certificate: `${baseUrl}certificates/javascript-dom.pdf` },
  { title: 'Asynchronous JavaScript', date: 'Jun 2025', certificate: `${baseUrl}certificates/asincronismo-javascript.pdf` },
  { title: 'Professional REST API Consumption with JavaScript', date: 'Aug 2025', certificate: `${baseUrl}certificates/api-rest-javascript.pdf` },
  { title: 'Node.js Fundamentals', date: 'Dec 2025', certificate: `${baseUrl}certificates/nodejs-fundamentals.pdf` },
  { title: 'React.js', date: 'Feb 2026', certificate: `${baseUrl}certificates/react-js.pdf` },
]
const ArrowIcon = () => <svg viewBox="0 0 20 20" aria-hidden="true" className="h-4 w-4" fill="none"><path d="M4 10h12m-5-5 5 5-5 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>
const GithubIcon = () => <svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5" fill="currentColor"><path d="M12 .7A11.5 11.5 0 0 0 8.36 23.1c.58.1.79-.25.79-.56v-2.23c-3.24.7-3.92-1.38-3.92-1.38-.53-1.35-1.3-1.7-1.3-1.7-1.06-.73.08-.72.08-.72 1.17.08 1.79 1.2 1.79 1.2 1.04 1.79 2.74 1.27 3.4.97.1-.76.4-1.27.74-1.56-2.58-.3-5.3-1.3-5.3-5.69 0-1.26.45-2.28 1.2-3.09-.12-.29-.52-1.47.11-3.05 0 0 .98-.31 3.16 1.18A10.9 10.9 0 0 1 12 6.08c.98 0 1.94.13 2.86.39 2.19-1.49 3.16-1.18 3.16-1.18.63 1.58.23 2.76.11 3.05.75.81 1.2 1.83 1.2 3.09 0 4.4-2.72 5.38-5.31 5.68.42.36.79 1.07.79 2.16v3.27c0 .31.21.67.8.56A11.5 11.5 0 0 0 12 .7Z" /></svg>
function SectionHeading({ eyebrow, title, description }) { return <div className="section-heading reveal"><p className="eyebrow">{eyebrow}</p><div className="section-heading__copy"><h2>{title}</h2>{description && <p>{description}</p>}</div></div> }

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add('is-visible')), { threshold: 0.12 }); const elements = document.querySelectorAll('.reveal'); elements.forEach((element) => observer.observe(element)); return () => observer.disconnect() }, [])
  return <div className="site-shell">
    <Header menuOpen={menuOpen} onMenuToggle={() => setMenuOpen((value) => !value)} onNavigate={() => setMenuOpen(false)} />
    <main>
      <section id="inicio" className="hero section-wrap" aria-labelledby="hero-title"><div className="hero__glow" aria-hidden="true" /><div className="hero__content reveal"><p className="availability"><span /> Open to web developer opportunities</p><h1 id="hero-title">I build websites <em>that are clear and functional.</em></h1><p className="hero__role">Junior Web Developer · IT Engineering Student</p><p className="hero__intro">I'm Maynor López. I build responsive interfaces with HTML, CSS, JavaScript and React.</p><div className="hero__actions"><a className="button button--primary" href="#proyectos">View projects <ArrowIcon /></a><a className="button button--ghost" href="https://github.com/mlopezl" target="_blank" rel="noreferrer"><GithubIcon /> GitHub</a></div></div><div className="hero__aside reveal" aria-hidden="true"><div className="code-card"><div className="code-card__top"><span /><span /><span /><small>maynor.jsx</small></div><pre><code><b>const</b> developer = {'{'}{`\n`}  name: <i>'Maynor López'</i>,{`\n`}  focus: <i>'User-friendly web'</i>,{`\n`}  mindset: <i>'Always learning'</i>{`\n`}{'}'}</code></pre></div><p className="hero__index">01 <span>/</span> 08</p></div></section>
      <section id="sobre-mi" className="section section-wrap"><SectionHeading eyebrow="01 / About" title="Curious mind. Practical approach." /><div className="about-grid"><div className="about-copy reveal"><p className="lead">I turn ideas into simple, useful web experiences.</p><p>I study IT Engineering at UNAN–León and build frontend projects with a focus on usability and mobile-friendly layouts.</p><p>As a <strong>Web Developer</strong>, I want to build and maintain website features, improve performance and collaborate with designers and marketers.</p><div className="about-values"><span>Dependable</span><span>Self-directed</span><span>Detail-oriented</span></div></div><div className="portrait-wrap reveal"><div className="portrait-frame"><img src={profileImage} alt="Professional portrait of Maynor López" /></div><div className="portrait-caption"><span>Based in</span><strong>León, Nicaragua</strong></div></div></div></section>
      <section id="habilidades" className="section section-wrap"><SectionHeading eyebrow="02 / Tech stack" title="My development toolkit." description="Frontend skills, everyday tools and my path toward full-stack." /><div className="skill-grid">{skills.map((skill) => <article className="skill-card reveal" key={skill.title}><span className="card-number">{skill.number}</span><h3>{skill.title}</h3><p>{skill.description}</p><div className="tag-list">{skill.items.map((item) => <span key={item}>{item}</span>)}</div></article>)}</div></section>
      <section id="proyectos" className="section section-wrap"><SectionHeading eyebrow="03 / Featured projects" title="Selected web projects." description="Hands-on work in responsive layouts, interactive features and form validation." /><div className="project-grid">{featuredProjects.map((project) => <article className="project-card reveal" key={project.number}><a className={`project-visual bg-gradient-to-br ${project.accent}`} href={project.live} target="_blank" rel="noreferrer" aria-label={`View ${project.title}`}><img src={project.image} alt={`Preview of ${project.title}`} loading="lazy" /><span>ML / {project.number}</span><strong>{project.number}</strong></a><div className="project-body"><div><p>Project {project.number}</p><h3>{project.title}</h3></div><p>{project.description}</p><div className="tag-list">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="project-links"><a href={project.live} target="_blank" rel="noreferrer">Demo <ArrowIcon /></a><a href={project.repo} target="_blank" rel="noreferrer"><GithubIcon /> Code</a></div></div></article>)}</div><div className="other-projects reveal"><div className="other-projects__heading"><p className="eyebrow">Other projects</p><span>More frontend practice</span></div>{otherProjects.map((project, index) => <div className="project-row" key={project.title}><span>0{index + 4}</span><a href={project.live} target="_blank" rel="noreferrer"><h3>{project.title}</h3></a><p>{project.category}</p><div className="row-links"><a href={project.repo} target="_blank" rel="noreferrer" aria-label={`Source code for ${project.title}`}><GithubIcon /></a><a href={project.live} target="_blank" rel="noreferrer" aria-label={`View ${project.title}`}><ArrowIcon /></a></div></div>)}</div></section>
      <section id="experiencia" className="section section-wrap"><SectionHeading eyebrow="04 / Experience" title="People skills. Practical experience." description="Communication, coordination and problem-solving from customer-facing roles." /><div className="experience-list">{experience.map((job) => <article className="experience-item reveal" key={`${job.company}-${job.role}`}><p>{job.period}</p><div><span>{job.company}</span><h3>{job.role}</h3></div><p>{job.summary}</p></article>)}</div></section>
      <section id="aprendiendo" className="learning section-wrap reveal"><p className="eyebrow">05 / Currently learning</p><div className="learning__content"><div><span className="pulse" /> Growing my backend skills</div><p><strong>JavaScript</strong><i>→</i><strong>Node.js</strong><i>→</i><strong>REST APIs</strong></p><small>Basic Node.js knowledge, backed by Platzi training. Also learning C#, .NET and ASP.NET Core.</small></div></section>
      <section id="educacion" className="section section-wrap"><SectionHeading eyebrow="06 / Education" title="A foundation for growth." /><div className="education-list"><article className="education-card reveal"><div className="education-year">In progress</div><div><p>National Autonomous University of Nicaragua</p><h3>Information Technology Engineering</h3><span>UNAN–León · 2023 — Present</span></div><div className="education-mark">UNAN</div></article><article className="education-card reveal"><div className="education-year">Completed</div><div><p>National Autonomous University of Nicaragua</p><h3>Bachelor’s Degree in Business Administration</h3><span>UNAN–León · 2012 — 2016</span></div><div className="education-mark">UNAN</div></article></div></section>
      <section id="cursos" className="section section-wrap"><SectionHeading eyebrow="07 / Additional training" title="Always learning." description="Completed Platzi courses in frontend development and Node.js fundamentals." /><div className="course-grid">{courses.map((course, index) => <a className="course-card reveal" href={course.certificate} target="_blank" rel="noreferrer" key={course.title}><div><span>0{index + 1}</span><p>Platzi · {course.date}</p></div><h3>{course.title}</h3><div className="course-card__link">View certificate <ArrowIcon /></div></a>)}</div></section>
      <section id="contacto" className="contact section-wrap reveal"><p className="eyebrow">08 / Contact</p><h2>Let's build something<br /><em>that works beautifully.</em></h2><p>Ready to contribute, keep learning and build better web experiences with your team.</p><div className="contact__actions"><a className="button button--primary" href="https://wa.me/50581378467?text=Hi%20Maynor%2C%20I%20saw%20your%20portfolio%20and%20would%20like%20to%20connect." target="_blank" rel="noreferrer">WhatsApp <ArrowIcon /></a><a className="button button--ghost" href="mailto:maynor94l39@gmail.com">Email <ArrowIcon /></a></div></section>
    </main>
    <footer className="footer section-wrap"><a href="#inicio" className="footer__brand">ML<span>.</span></a><p>Designed and developed by Maynor López</p><p>© {new Date().getFullYear()} · León, Nicaragua</p></footer>
  </div>
}
export default App
