import { useEffect, useState } from 'react'
import './App.css'
import profileImage from '../public/profile.png'
import Header from './components/Header'

const baseUrl = import.meta.env.BASE_URL

const skills = [
  { number: '01', title: 'Frontend', description: 'Interfaces claras, rápidas y adaptables a cualquier dispositivo.', items: ['HTML5', 'CSS3', 'JavaScript', 'React', 'Tailwind CSS'] },
  { number: '02', title: 'Herramientas', description: 'Un flujo enfocado en calidad, colaboración y mantenimiento.', items: ['Git', 'GitHub', 'Vite', 'Figma', 'VS Code'] },
  { number: '03', title: 'En aprendizaje', description: 'Ampliando mi perfil para crear soluciones web de principio a fin.', items: ['C#', '.NET', 'ASP.NET Core', 'APIs REST', 'SEO y analítica'] },
]
const featuredProjects = [
  { number: '01', title: 'Lista de productos y carrito', description: 'Catálogo responsive con carrito, cantidades y confirmación de compra.', tags: ['JavaScript', 'Responsive', 'Estado UI'], live: 'https://mlopezl.github.io/product-list-with-card/', repo: 'https://github.com/mlopezl/product-list-with-card', image: `${baseUrl}projects/product-cart.jpg`, accent: 'from-emerald-500/25 to-indigo-500/5' },
  { number: '02', title: 'Gestor de extensiones', description: 'Panel para filtrar, activar y administrar extensiones.', tags: ['JavaScript', 'Filtros', 'UI responsive'], live: 'https://mlopezl.github.io/my-version-of-browser-extensions-manager-ui-main-challenge/', repo: 'https://github.com/mlopezl/my-version-of-browser-extensions-manager-ui-main-challenge', image: `${baseUrl}projects/extension-manager.jpg`, accent: 'from-indigo-500/25 to-emerald-500/5' },
  { number: '03', title: 'Formulario de contacto', description: 'Formulario accesible con validación y estados de error claros.', tags: ['HTML5', 'CSS3', 'Validación'], live: 'https://mlopezl.github.io/contact-info-form-challenge/', repo: 'https://github.com/mlopezl/contact-info-form-challenge', image: `${baseUrl}projects/contact-form.jpg`, accent: 'from-emerald-400/20 to-cyan-500/5' },
]
const otherProjects = [
  { title: 'Dashboard de redes sociales', category: 'Temas claro y oscuro', live: 'https://mlopezl.github.io/social-media-dashboard-with-theme-switcher/', repo: 'https://github.com/mlopezl/social-media-dashboard-with-theme-switcher' },
  { title: 'Calculadora de propinas', category: 'Cálculos e interacción', live: 'https://mlopezl.github.io/tip-calculator-app-challenge/', repo: 'https://github.com/mlopezl/tip-calculator-app-challenge' },
  { title: 'Generador de ticket', category: 'Formulario y vista previa', live: 'https://mlopezl.github.io/My-version-of-conference-ticket-generator-challenge/', repo: 'https://github.com/mlopezl/My-version-of-conference-ticket-generator-challenge' },
  { title: 'Insure landing page', category: 'Maquetación responsive', live: 'https://mlopezl.github.io/Insure-Landing-Page/', repo: 'https://github.com/mlopezl/Insure-Landing-Page' },
]
const experience = [
  { period: '2022 — Actualidad', role: 'Representante de servicio al cliente', company: 'D&R', summary: 'Atención de consultas, resolución de problemas y seguimiento para asegurar una buena experiencia.' },
  { period: '2020 — 2022', role: 'Reclutador profesional', company: 'Accedo Technologies', summary: 'Selección de candidatos, entrevistas telefónicas y coordinación del proceso de contratación.' },
  { period: '2017 — 2022', role: 'Supervisor de responsabilidad social', company: 'Ingenio San Antonio', summary: 'Coordinación de programas comunitarios y trabajo con equipos en proyectos de educación, salud e infraestructura.' },
]
const courses = [
  { title: 'HTML y CSS a profundidad', date: 'Feb 2025', certificate: `${baseUrl}certificates/html-css-profundo.pdf` },
  { title: 'Fundamentos de JavaScript', date: 'Mar 2025', certificate: `${baseUrl}certificates/fundamentos-javascript.pdf` },
  { title: 'JavaScript: manipulación del DOM', date: 'Mar 2025', certificate: `${baseUrl}certificates/javascript-dom.pdf` },
  { title: 'Asincronismo con JavaScript', date: 'Jun 2025', certificate: `${baseUrl}certificates/asincronismo-javascript.pdf` },
  { title: 'Consumo de API REST con JavaScript', date: 'Ago 2025', certificate: `${baseUrl}certificates/api-rest-javascript.pdf` },
  { title: 'React.js', date: 'Feb 2026', certificate: `${baseUrl}certificates/react-js.pdf` },
]
const ArrowIcon = () => <svg viewBox="0 0 20 20" aria-hidden="true" className="h-4 w-4" fill="none"><path d="M4 10h12m-5-5 5 5-5 5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg>
const GithubIcon = () => <svg viewBox="0 0 24 24" aria-hidden="true" className="h-5 w-5" fill="currentColor"><path d="M12 .7A11.5 11.5 0 0 0 8.36 23.1c.58.1.79-.25.79-.56v-2.23c-3.24.7-3.92-1.38-3.92-1.38-.53-1.35-1.3-1.7-1.3-1.7-1.06-.73.08-.72.08-.72 1.17.08 1.79 1.2 1.79 1.2 1.04 1.79 2.74 1.27 3.4.97.1-.76.4-1.27.74-1.56-2.58-.3-5.3-1.3-5.3-5.69 0-1.26.45-2.28 1.2-3.09-.12-.29-.52-1.47.11-3.05 0 0 .98-.31 3.16 1.18A10.9 10.9 0 0 1 12 6.08c.98 0 1.94.13 2.86.39 2.19-1.49 3.16-1.18 3.16-1.18.63 1.58.23 2.76.11 3.05.75.81 1.2 1.83 1.2 3.09 0 4.4-2.72 5.38-5.31 5.68.42.36.79 1.07.79 2.16v3.27c0 .31.21.67.8.56A11.5 11.5 0 0 0 12 .7Z" /></svg>
function SectionHeading({ eyebrow, title, description }) { return <div className="section-heading reveal"><p className="eyebrow">{eyebrow}</p><div className="section-heading__copy"><h2>{title}</h2>{description && <p>{description}</p>}</div></div> }

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add('is-visible')), { threshold: 0.12 }); const elements = document.querySelectorAll('.reveal'); elements.forEach((element) => observer.observe(element)); return () => observer.disconnect() }, [])
  return <div className="site-shell">
    <Header menuOpen={menuOpen} onMenuToggle={() => setMenuOpen((value) => !value)} onNavigate={() => setMenuOpen(false)} />
    <main>
      <section id="inicio" className="hero section-wrap" aria-labelledby="hero-title"><div className="hero__glow" aria-hidden="true" /><div className="hero__content reveal"><p className="availability"><span /> Disponible para nuevas oportunidades</p><h1 id="hero-title">Creo sitios web <em>claros y funcionales.</em></h1><p className="hero__role">Estudiante de Ingeniería TI · Desarrollador web en formación</p><p className="hero__intro">Soy Maynor López. Construyo interfaces responsive y fáciles de mantener.</p><div className="hero__actions"><a className="button button--primary" href="#proyectos">Proyectos <ArrowIcon /></a><a className="button button--ghost" href="https://github.com/mlopezl" target="_blank" rel="noreferrer"><GithubIcon /> GitHub</a></div></div><div className="hero__aside reveal" aria-hidden="true"><div className="code-card"><div className="code-card__top"><span /><span /><span /><small>maynor.jsx</small></div><pre><code><b>const</b> developer = {'{'}{`\n`}  name: <i>'Maynor López'</i>,{`\n`}  focus: <i>'Web de calidad'</i>,{`\n`}  mindset: <i>'Siempre aprendiendo'</i>{`\n`}{'}'}</code></pre></div><p className="hero__index">01 <span>/</span> 08</p></div></section>
      <section id="sobre-mi" className="section section-wrap"><SectionHeading eyebrow="01 / Sobre mí" title="Curiosidad técnica, enfoque práctico." /><div className="about-grid"><div className="about-copy reveal"><p className="lead">Convierto ideas en experiencias web simples y útiles.</p><p>Estudio Ingeniería TI en la UNAN–León y desarrollo proyectos frontend para fortalecer mis habilidades.</p><p>Busco aportar como <strong>Webmaster Junior</strong> en mantenimiento, contenido y mejora continua de sitios web.</p><div className="about-values"><span>Responsable</span><span>Autodidacta</span><span>Orientado al detalle</span></div></div><div className="portrait-wrap reveal"><div className="portrait-frame"><img src={profileImage} alt="Retrato profesional de Maynor López" /></div><div className="portrait-caption"><span>Basado en</span><strong>León, Nicaragua</strong></div></div></div></section>
      <section id="habilidades" className="section section-wrap"><SectionHeading eyebrow="02 / Stack técnico" title="Tecnologías que uso." description="Frontend, herramientas de trabajo y mi ruta hacia full-stack." /><div className="skill-grid">{skills.map((skill) => <article className="skill-card reveal" key={skill.title}><span className="card-number">{skill.number}</span><h3>{skill.title}</h3><p>{skill.description}</p><div className="tag-list">{skill.items.map((item) => <span key={item}>{item}</span>)}</div></article>)}</div></section>
      <section id="proyectos" className="section section-wrap"><SectionHeading eyebrow="03 / Proyectos destacados" title="Proyectos reales." description="Interacción, responsive y atención al detalle." /><div className="project-grid">{featuredProjects.map((project) => <article className="project-card reveal" key={project.number}><a className={`project-visual bg-gradient-to-br ${project.accent}`} href={project.live} target="_blank" rel="noreferrer" aria-label={`Ver ${project.title}`}><img src={project.image} alt={`Vista previa de ${project.title}`} loading="lazy" /><span>ML / {project.number}</span><strong>{project.number}</strong></a><div className="project-body"><div><p>Proyecto {project.number}</p><h3>{project.title}</h3></div><p>{project.description}</p><div className="tag-list">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div><div className="project-links"><a href={project.live} target="_blank" rel="noreferrer">Demo <ArrowIcon /></a><a href={project.repo} target="_blank" rel="noreferrer"><GithubIcon /> Código</a></div></div></article>)}</div><div className="other-projects reveal"><div className="other-projects__heading"><p className="eyebrow">Otros proyectos</p><span>Más ejercicios frontend</span></div>{otherProjects.map((project, index) => <div className="project-row" key={project.title}><span>0{index + 4}</span><a href={project.live} target="_blank" rel="noreferrer"><h3>{project.title}</h3></a><p>{project.category}</p><div className="row-links"><a href={project.repo} target="_blank" rel="noreferrer" aria-label={`Código de ${project.title}`}><GithubIcon /></a><a href={project.live} target="_blank" rel="noreferrer" aria-label={`Ver ${project.title}`}><ArrowIcon /></a></div></div>)}</div></section>
      <section id="experiencia" className="section section-wrap"><SectionHeading eyebrow="04 / Experiencia" title="Experiencia que suma." description="Comunicación, organización y resolución de problemas en entornos profesionales." /><div className="experience-list">{experience.map((job) => <article className="experience-item reveal" key={`${job.company}-${job.role}`}><p>{job.period}</p><div><span>{job.company}</span><h3>{job.role}</h3></div><p>{job.summary}</p></article>)}</div></section>
      <section id="aprendiendo" className="learning section-wrap reveal"><p className="eyebrow">05 / Actualmente aprendiendo</p><div className="learning__content"><div><span className="pulse" /> Próximo objetivo</div><p><strong>C#</strong><i>→</i><strong>.NET</strong><i>→</i><strong>ASP.NET Core</strong><i>→</i><strong>APIs</strong></p><small>Avanzando hacia el desarrollo full-stack.</small></div></section>
      <section id="educacion" className="section section-wrap"><SectionHeading eyebrow="06 / Educación" title="Una base para seguir creciendo." /><div className="education-list"><article className="education-card reveal"><div className="education-year">En curso</div><div><p>Universidad Nacional Autónoma de Nicaragua</p><h3>Ingeniería en Tecnologías de la Información</h3><span>UNAN–León · 2023 — Actualidad</span></div><div className="education-mark">UNAN</div></article><article className="education-card reveal"><div className="education-year">Completada</div><div><p>Universidad Nacional Autónoma de Nicaragua</p><h3>Licenciatura en Administración de Empresas</h3><span>UNAN–León · 2012 — 2016</span></div><div className="education-mark">UNAN</div></article></div></section>
      <section id="cursos" className="section section-wrap"><SectionHeading eyebrow="07 / Formación complementaria" title="Aprendizaje continuo." description="Cursos de Platzi que respaldan mi formación frontend." /><div className="course-grid">{courses.map((course, index) => <a className="course-card reveal" href={course.certificate} target="_blank" rel="noreferrer" key={course.title}><div><span>0{index + 1}</span><p>Platzi · {course.date}</p></div><h3>{course.title}</h3><div className="course-card__link">Ver certificado <ArrowIcon /></div></a>)}</div></section>
      <section id="contacto" className="contact section-wrap reveal"><p className="eyebrow">08 / Contacto</p><h2>Construyamos algo<br /><em>que funcione de verdad.</em></h2><p>Estoy listo para aportar, aprender y asumir nuevos retos en un equipo de desarrollo web.</p><div className="contact__actions"><a className="button button--primary" href="https://wa.me/50581378467?text=Hola%20Maynor%2C%20vi%20tu%20portafolio%20y%20me%20gustar%C3%ADa%20conversar%20contigo." target="_blank" rel="noreferrer">WhatsApp <ArrowIcon /></a><a className="button button--ghost" href="mailto:maynor94l39@gmail.com">Correo <ArrowIcon /></a></div></section>
    </main>
    <footer className="footer section-wrap"><a href="#inicio" className="footer__brand">ML<span>.</span></a><p>Diseñado y desarrollado por Maynor López</p><p>© {new Date().getFullYear()} · León, Nicaragua</p></footer>
  </div>
}
export default App
